language: php

php:
  - 5.3
  - 5.4
  - 5.5

env:
  - DB=mysql CAKEPHP=2.4.10
  - DB=mysql CAKEPHP=2.5.7
  - DB=mysql CAKEPHP=2.6.0

before_script:
  - composer install --dev
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'DROP DATABASE IF EXISTS cakephp_test;'; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE cakephp_test;'; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'CREATE DATABASE cakephp_test;' -U postgres; fi"
  - wget https://github.com/cakephp/cakephp/tarball/$CAKEPHP -O cake.tar.gz
  - tar xf cake.tar.gz
  - mv cakephp-cakephp-* ./cakephp
  - mv Test/database.php cakephp/app/Config/database.php
  - mkdir -p ./cakephp/app/Plugin/Setting
  - mv Model ./cakephp/app/Plugin/Setting
  - mv Test ./cakephp/app/Plugin/Setting
  - mv Config ./cakephp/app/Plugin/Setting
  - chmod -R 777 ./cakephp/app/tmp
  - echo "<?php
    CakePlugin::load('Setting', array('bootstrap' => true));
    ini_set('include_path',  '/home/travis/build/k1LoW/Setting/vendor/phpunit/phpunit' . PATH_SEPARATOR . ini_get('include_path'));
    " > cakephp/app/Config/bootstrap.php
  - echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?>
    <phpunit bootstrap=\"vendor/autoload.php\">
    <filter>
        <blacklist>
            <directory suffix=\".php\">app/Config</directory>
            <directory suffix=\".php\">app/Controller</directory>
            <directory suffix=\".php\">app/Model</directory>
            <directory suffix=\".php\">app/Test</directory>
            <directory suffix=\".php\">app/Vendor</directory>
            <directory suffix=\".php\">app/Plugin/Setting/Test</directory>
            <directory suffix=\".php\">lib</directory>
            <directory suffix=\".php\">vendor</directory>
        </blacklist>
    </filter>
    </phpunit>
    " > cakephp/phpunit.xml.dist
  - mv coveralls.json cakephp/composer.json
  - mv .coveralls.yml cakephp/.coveralls.yml
  - cd ./cakephp
  - composer install --dev --no-interaction --prefer-source
  - mkdir -p build/logs

script:
  - ./lib/Cake/Console/cake test Setting All --stderr --coverage-clover build/logs/clover.xml --configuration phpunit.xml.dist

after_script:
  - php vendor/bin/coveralls -v
