language: php

php:
  - 5.2
  - 5.3

env:
  - DB=mysql CAKEPHP=2.1.4
  - DB=mysql CAKEPHP=2.2.0
  - DB=pgsql CAKEPHP=2.1.4
  - DB=pgsql CAKEPHP=2.2.0

before_script:
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE cakephp_test;'; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'CREATE DATABASE cakephp_test;' -U postgres; fi"
  - wget https://github.com/cakephp/cakephp/tarball/$CAKEPHP -O cake.tar.gz
  - tar xf cake.tar.gz
  - mv cakephp-cakephp-* ./cakephp
  - chmod -R 777 ./cakephp/app/tmp
  - echo "<?php
    App::build(array(
    'Plugin' => array('/home/vagrant/builds/k1LoW/'),
    ));
    CakePlugin::load('Setting', array('bootstrap' => true));
    " > cakephp/app/Config/bootstrap.php
  - mv Test/database.php cakephp/app/Config/database.php
  - cd ./cakephp

script:
  - ./lib/Cake/Console/cake test Setting Model/Setting --stderr

after_script:
  - rm -rf ../Setting